### ISSUE TITLE
FAILED to withdraw my xDAI !!!

### ISSUE THREAD

**Issue by harry830622** [jannikluhn/graffiti#47]
I tried to withdraw 720 xDAI but got only 0.576981125327486976 xDAI, thus losing almost all of the withdrawal 😭
Is it possible to get refund?

BTW, after some testing, I found that only if the withdrawal is greater than 10 xDAI, the amount of xDAI withdrawn to wallet will be wrong.

FYI, here is my tx:
https://blockscout.com/poa/xdai/tx/0x2b5dfd52f5373326af37df16e347bd7a795d20121d6ee3b1ef149d18907a4a15/internal-transactions

**Comment by jannikluhn** [comment]
Thank you very much for reporting. We have already frozen the site and are investigating. Really sorry about this, we'll keep you updated!

**Comment by harry830622** [comment]
Any updates?

**Comment by jannikluhn** [comment]
We found the issue and unfortunately it looks like the funds are stuck and not recoverable :( We fixed the issue and added a safety net to prevent this in the future, but it's too late for the existing contract and all we can do is deploy a new version which we will do soon. We are very sorry for what happened (it's an unfortunate hazard of being a time-crunched hackathon project, and why we stuck that warning on the how to page).

Your analysis is correct that withdrawing works only with small amounts (which is why we didn't see the issue during testing). If you're curious, it's an integer overflow in [this line](https://github.com/jannikluhn/graffiti/blob/main/contracts/contracts/Graffiti.sol#L357). The balance is updated correctly, but the amount sent out is limited to ~18xDai. Deposits that haven't been withdrawn yet are safe as long as one withdraws them in small batches only.

**Comment by harry830622** [comment]
Okay then when will the bug be fixed?
Also, although the fund is not recoverable, is there any alternative way to compensate my loss ($720 USD)?
For example, share certain percentage of tax with me, or mint say like graffti tokens and airdrop me some.
Thanks

**Comment by jannikluhn** [comment]
Hi Harry, good news… We rescued the funds! We have restored them to a new, fixed implementation of GraffitETH and you may safely withdraw now. Thanks for being a good sport about it and thanks for being an early graffitier!!!

Also, we have handmade a special NFT for you, as a token of apology and appreciation from our team. It is in your wallet. Sorry for the trouble!

**Comment by harry830622** [comment]
WOW, thought I will never get it back.
Amazing work, really appreciate the effort.
Thank you and keep it up!
